.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "LINECOOK" "1" "December 2016" "1.0.2
" ""
.
.SH "NAME"
\fBlinecook\fR \- render ERB templates
.
.SH "SYNOPSIS"
\fBlinecook\fR \fIoptions\fR TEMPLATES\.\.\.
.
.SH "DESCRIPTION"
\fBlinecook\fR renders ERB templates\. Templates have access to an \'obj\' (typically a hash) read from an attributes file as YAML\. When multiple (documents are present in the attributes file the templates will render (multiple times\.
.
.P
All files in a directory are rendered when specified as a template\. Options are provided to render results to an output directory\.
.
.SH "OPTIONS"
These options control how \fBlinecook\fR operates\.
.
.TP
\fB\-A FILE\fR
Read attrs as lines from FILE\. STDIN can be specified as \'\-\'\.Each line is parsed as YAML into an object\.
.
.TP
\fB\-a FILE\fR
Read attrs as YAML documents from FILE\. STDIN can be specified as \'\-\'\.
.
.TP
\fB\-e\fR
Treat TEMPLATE as the template string\.
.
.TP
\fB\-f\fR, \fB\-\-[no\-]force\fR
Remove the target directory if it exists on \'\-o\'\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help\.
.
.TP
\fB\-o TARGET_DIR\fR
Output results to the target dir, which will be created if it does not exist\. Templates are rendered using their basename; in the case of a directory the output files will preserve the relative path to the template\.Multiple rendering are appended to each file\.
.
.TP
\fB\-r RUBY_FILE\fR
Require the specified ruby file\. Use this to expand the Linecook::Context class to make templates more intelligent\.
.
.SH "ENVIRONMENT"
\fBlinecook\fR reserves all variables starting with \'LINECOOK_\' for internal use\.
.
.SH "INSTALLATION"
Add \fBlinecook\fR to your PATH (or execute it directly)\. A nice way of doing so is to clone the repo and add the bin dir to PATH\. This allows easy updates via \fBgit pull\fR and should make the manpages available via \fBman linecook\fR\.
.
.IP "" 4
.
.nf

git clone git://github\.com/goodlittlescript/linecook\.git
export PATH="$PWD/linecook/bin:$PATH"
.
.fi
.
.IP "" 0
.
.P
If you\'re using homebrew \fIhttp://brew\.sh/\fR on OSX you can tap goodlittlescript \fIhttps://github\.com/goodlittlescript/homebrew\-gls\fR\.
.
.IP "" 4
.
.nf

brew tap goodlittlescript/homebrew\-gls
brew install linecook
.
.fi
.
.IP "" 0
.
.SH "DEVELOPMENT"
Clone the repo as above\. To run the tests (written in \fBts\fR \- see https://github\.com/thinkerbot/ts for installation instruction):
.
.IP "" 4
.
.nf

\[char46]/test/suite
.
.fi
.
.IP "" 0
.
.P
To generate the manpages:
.
.IP "" 4
.
.nf

rake manpages
.
.fi
.
.IP "" 0
.
.P
Report bugs here: http://github\.com/goodlittlescript/linecook/issues\.
.
.SH "COPYRIGHT"
Linecook is Copyright (C) 2015 Simon Chiang \fIhttp://github\.com/thinkerbot\fR
