#!/bin/bash
. test/integration/helper

# helpers

setup_template_file () {
template_name="example"
template_file="$ts_test_dir/$template_name.erb"
mkdir -p "$ts_test_dir"
printf "%s" "$1" > "$template_file"
printf "%s\n" "$template_file"
}

setup_attributes_file () {
template_name="example"
attributes_file="$ts_test_dir/$template_name.yml"
mkdir -p "$ts_test_dir"
printf "%s" "$1" > "$attributes_file"
printf "%s\n" "$attributes_file"
}

#
# lc tests
#

test_lc_renders_file_with_args () {
setup_template_file "1 + 2 = <%= args.map(&:to_i).inject(0, &:+) %>"
lc "$template_file" 1 2 | assert_output "1 + 2 = 3"
}

test_lc_assigns_argnames_according_to_attributes_file () {
setup_template_file "1 + 2 = <%= a.to_i + b.to_i %>"
setup_attributes_file "\
args: [a, b]
"

lc "$template_file" 1 2 | assert_output "1 + 2 = 3"
}

test_lc_looks_up_template_file_along_LC_PATH () {
setup_template_file "<%= 1 + 2 %>"
export LC_PATH="$ts_test_dir"
lc "$template_name" | assert_output "3"
}

test_lc_prints_error_if_template_cannot_be_found_on_LC_PATH () {
export LC_PATH="$ts_test_dir"
lc missing 2>&1 | assert_output "\
could not find template: \"missing\"
"
}

#
# -f
#

test_lc_f_renders_template_for_each_line_in_csv_inputs () {
setup_template_file "\
got <%= args.join(' ') %>
"

csv_file_one="$ts_test_dir/one.csv"
printf "%s,%s,%s\n" a b c i j k > "$csv_file_one"

csv_file_two="$ts_test_dir/two.csv"
printf "%s,%s,%s\n" x y z > "$csv_file_two"

printf "%s,%s,%s\n" p q r |
lc -f "$template_file" "$csv_file_one" - "$csv_file_two" | assert_output "\
got a b c
got i j k
got p q r
got x y z
"
}

#
# -l
#

test_lc_l_prints_list_of_templates_on_LC_PATH () {
mkdir -p "$ts_test_dir"
touch "$ts_test_dir/abc.erb"
touch "$ts_test_dir/xyz.erb"
export LC_PATH="$ts_test_dir"
lc -l | assert_output "\
abc
xyz
"
}

#
# -h
#

test_lc_h_prints_help () {
lc -h | grep -q "usage: lc"
}

. ts
