#!/bin/bash
. test/integration/helper

# helpers

setup_template_file () {
template_name="example"
template_file="$ts_test_dir/$template_name.erb"
mkdir -p "$ts_test_dir"
printf "%s" "$1" > "$template_file"
}

setup_attributes_file () {
template_name="example"
attributes_file="$ts_test_dir/$template_name.yml"
mkdir -p "$ts_test_dir"
printf "%s" "$1" > "$attributes_file"
}

#
# linecook tests
#

test_linecook_renders_file_with_args () {
setup_template_file "1 + 2 = <%= args.map(&:to_i).inject(0, &:+) %>"
linecook "$template_file" 1 2 | assert_output "1 + 2 = 3"
}

test_linecook_assigns_argnames_according_to_attributes_file () {
setup_template_file "1 + 2 = <%= a.to_i + b.to_i %>"
setup_attributes_file "\
args: [a, b]
"

linecook "$template_file" 1 2 | assert_output "1 + 2 = 3"
}

test_linecook_assigns_defaults_according_to_attributes_file () {
setup_template_file "1 + 2 = <%= a.to_i + b.to_i %>"
setup_attributes_file "\
args:
  a: 0
  b: 2
"

linecook "$template_file" 1 | assert_output "1 + 2 = 3"
}

test_linecook_recognizes_attributes_in_lc_files () {
mkdir -p "$ts_test_dir/dir"
cat > "$ts_test_dir/example.lc" <<DOC
args:
  a: 0
  b: 2
---
1 + 2 = <%= a.to_i + b.to_i %>
DOC

linecook "$ts_test_dir/example.lc" 1 | assert_output "\
1 + 2 = 3
"
}

test_linecook_looks_up_template_file_along_LINECOOK_PATH () {
setup_template_file "<%= 1 + 2 %>"
export LINECOOK_PATH="$ts_test_dir"
linecook "$template_name" | assert_output "3"
}

test_linecook_can_find_template_files_under_dir () {
mkdir -p "$ts_test_dir/dir"
printf "%s" "<%= 1 + 2 %>" > "$ts_test_dir/dir/template.erb"

export LINECOOK_PATH="$ts_test_dir"
linecook dir/template | assert_output "3"
}

test_linecook_prints_error_if_template_cannot_be_found_on_LINECOOK_PATH () {
export LINECOOK_PATH="$ts_test_dir"
linecook missing 2>&1 | assert_output "\
could not find template: \"missing\"
"
}

test_linecook_prints_error_if_no_template_is_specified () {
linecook 2>&1 | assert_output "\
no template specified
"
}

#
# -f
#

test_linecook_f_renders_template_for_each_line_in_csv_inputs () {
setup_template_file "\
got <%= args.join(' ') %>
"

csv_file_one="$ts_test_dir/one.csv"
printf "%s,%s,%s\n" a b c i j k > "$csv_file_one"

csv_file_two="$ts_test_dir/two.csv"
printf "%s,%s,%s\n" x y z > "$csv_file_two"

printf "%s,%s,%s\n" p q r |
linecook -f "$template_file" "$csv_file_one" - "$csv_file_two" | assert_output "\
got a b c
got i j k
got p q r
got x y z
"
}

#
# -F
#

test_linecook_F_sets_field_sep_for_csv_inputs () {
setup_template_file "\
got <%= args.join(' ') %>
"
printf "%s|%s|%s\n" a b c x y z |
linecook -F '|' "$template_file" | assert_output "\
got a b c
got x y z
"
}

#
# -H
#

test_linecook_H_specifies_each_csv_file_has_headers () {
setup_template_file "\
got <%= args.join(' ') %>
"

csv_file_one="$ts_test_dir/one.csv"
printf "%s,%s,%s\n" A B C a b c i j k > "$csv_file_one"

csv_file_two="$ts_test_dir/two.csv"
printf "%s,%s,%s\n" A B C x y z > "$csv_file_two"

printf "%s,%s,%s\n" A B C p q r |
linecook -H "$template_file" "$csv_file_one" - "$csv_file_two" | assert_output "\
got a b c
got i j k
got p q r
got x y z
"
}

test_linecook_H_maps_csv_fields_to_named_args_on_a_per_file_basis () {
setup_template_file "\
got <%= self.A %> <%= self.B %> <%= self.C %>
"
setup_attributes_file "\
args:
  A: a
  B: b
  C: c
"

# extra fields
csv_file_one="$ts_test_dir/one.csv"
printf "%s,%s,%s,%s\n" A B C D a b c d i j k l > "$csv_file_one"

# out-of-order fields
csv_file_two="$ts_test_dir/two.csv"
printf "%s,%s,%s\n" B C A y z x > "$csv_file_two"

# missing fields
printf "%s,%s\n" A B p q |
linecook -H "$template_file" "$csv_file_one" - "$csv_file_two" | assert_output "\
got a b c
got i j k
got p q c
got x y z
"
}

#
# -I
#

test_linecook_I_sets_LINECOOK_PATH () {
setup_template_file "<%= 1 + 2 %>"
linecook -I "$ts_test_dir" "$template_name" | assert_output "3"
}

#
# -L
#

test_linecook_L_prints_list_of_matching_templates_on_LINECOOK_PATH () {
mkdir -p "$ts_test_dir"
touch "$ts_test_dir/abc.erb"
touch "$ts_test_dir/abd.erb"
touch "$ts_test_dir/a.erb"
touch "$ts_test_dir/ax.erb"

export LINECOOK_PATH="$ts_test_dir"
linecook -L ab | assert_output "\
abc
abd
"
}

test_linecook_L_prints_all_templates_if_no_template_is_specified () {
mkdir -p "$ts_test_dir"
touch "$ts_test_dir/abc.erb"
touch "$ts_test_dir/xyz.erb"

export LINECOOK_PATH="$ts_test_dir"
linecook -L | assert_output "\
abc
xyz
"
}

#
# -l
#

test_linecook_l_prints_list_of_templates_on_LINECOOK_PATH () {
mkdir -p "$ts_test_dir"
touch "$ts_test_dir/abc.erb"
touch "$ts_test_dir/xyz.erb"
export LINECOOK_PATH="$ts_test_dir"
linecook -l | assert_output "\
abc
xyz
"
}

test_linecook_l_prints_desc_as_in_attributes_file_if_present () {
mkdir -p "$ts_test_dir"

touch "$ts_test_dir/abc.erb"
cat > "$ts_test_dir/abc.yml" <<DOC
desc: "the abc template"
DOC

touch "$ts_test_dir/xyz.erb"
cat > "$ts_test_dir/xyz.yml" <<DOC
# no desc
DOC

export LINECOOK_PATH="$ts_test_dir"
linecook -l | assert_output "\
abc    the abc template
xyz
"
}

#
# -h
#

test_linecook_h_prints_help () {
linecook -h | grep -q "usage: linecook"
}

. ts
